services:
  - type: web
    name: wanderlust-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run dev:server
    envVars:
      - key: NODE_ENV
        value: production
