import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { tmpdir } from 'node:os';
import { travelData, packagesData } from '../src/mockData.js';

const dbPath = process.env.VERCEL
  ? join(tmpdir(), 'voyara-db.json')
  : join(process.cwd(), 'server', 'data', 'db.json');

async function readDb() {
  try {
    const raw = await readFile(dbPath, 'utf8');
    const data = JSON.parse(raw);
    return {
      bookings: data.bookings || [],
      packages: data.packages || [],
    };
  } catch {
    return { bookings: [], packages: [] };
  }
}

async function writeDb(data) {
  await mkdir(dirname(dbPath), { recursive: true });
  await writeFile(dbPath, JSON.stringify(data, null, 2));
}

function sendJson(res, status, data) {
  res.status(status).json(data);
}

function validateBooking(body) {
  const required = ['vehicleName', 'route', 'seats', 'amount', 'traveler'];
  const missing = required.filter((key) => body[key] === undefined || body[key] === null || body[key] === '');
  if (missing.length) return `Missing fields: ${missing.join(', ')}`;
  if (!Array.isArray(body.seats) || body.seats.length === 0) return 'At least one seat is required';
  if (!body.traveler.name || !body.traveler.email || !body.traveler.phone) return 'Traveler name, email, and phone are required';
  return null;
}

function escapePdfText(value) {
  return String(value || '')
    .replaceAll('\\', '\\\\')
    .replaceAll('(', '\\(')
    .replaceAll(')', '\\)');
}

function createTicketPdf(booking) {
  const lines = [
    'VOYARA TRAVEL',
    'Confirmed Travel Ticket',
    '',
    `Booking ID: ${booking.id}`,
    `Passenger: ${booking.traveler?.name || 'Traveler'}`,
    `Route: ${booking.route}`,
    `Service: ${booking.vehicleName}`,
    `Type: ${booking.vehicleType}`,
    `Seats/Room: ${(booking.seats || []).join(', ')}`,
    `Amount: Rs. ${Number(booking.amount || 0).toLocaleString('en-IN')}`,
    `Payment: ${booking.paymentStatus}`,
    `Status: ${booking.status}`,
    `Booked On: ${new Date(booking.createdAt).toLocaleString('en-IN')}`,
    '',
    'Please carry a valid government ID during travel.',
    'This is a portfolio demo ticket generated by the Voyara backend.',
  ];

  const text = lines
    .map((line, index) => `BT /F1 ${index < 2 ? 20 : 12} Tf 72 ${760 - index * 28} Td (${escapePdfText(line)}) Tj ET`)
    .join('\n');
  const stream = `<< /Length ${Buffer.byteLength(text)} >>\nstream\n${text}\nendstream`;
  const objects = [
    '1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj',
    '2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj',
    '3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >> endobj',
    '4 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >> endobj',
    `5 0 obj ${stream} endobj`,
  ];
  let pdf = '%PDF-1.4\n';
  const offsets = [0];
  for (const object of objects) {
    offsets.push(Buffer.byteLength(pdf));
    pdf += `${object}\n`;
  }
  const xrefStart = Buffer.byteLength(pdf);
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (let i = 1; i < offsets.length; i += 1) {
    pdf += `${String(offsets[i]).padStart(10, '0')} 00000 n \n`;
  }
  pdf += `trailer << /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF`;
  return Buffer.from(pdf);
}

function createAiPlan(body = {}) {
  const destination = body.destination || 'Dubai';
  const days = Math.max(1, Math.min(Number(body.days || 4), 10));
  const budget = Number(body.budget || 60000);
  const style = body.style || 'Balanced';
  const pace = budget > 150000 ? 'premium' : budget > 60000 ? 'comfort' : 'smart budget';
  const dayIdeas = [
    'arrival, hotel check-in, nearby food street, and evening viewpoint',
    'landmark sightseeing, local market, and guided cultural experience',
    'adventure or nature activity with a relaxed cafe break',
    'premium experience, sunset spot, and shopping district',
    'hidden gems, photo stops, and local food crawl',
    'museum or heritage walk with leisure time',
    'free morning, souvenir shopping, and departure planning',
  ];

  return {
    title: `${days}-day ${destination} ${style.toLowerCase()} plan`,
    summary: `A ${pace} itinerary for ${destination} built around ${days} days, Rs. ${budget.toLocaleString('en-IN')} budget, and ${style.toLowerCase()} travel style.`,
    estimatedBudget: budget,
    days: Array.from({ length: days }, (_, index) => ({
      day: index + 1,
      title: `Day ${index + 1}: ${destination} ${index === 0 ? 'arrival and essentials' : 'experience route'}`,
      plan: dayIdeas[index % dayIdeas.length],
      tip: index === 0 ? 'Keep the first evening light after travel.' : 'Pre-book popular attractions to avoid queues.',
    })),
    packing: ['Valid ID/passport', 'Comfortable walking shoes', 'Power bank', 'Weather-ready outfit', 'Digital ticket copies'],
    safety: ['Share hotel and route with family', 'Keep emergency contacts offline', 'Use verified transport providers'],
  };
}

export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET,POST,OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') {
    res.status(204).end();
    return;
  }

  const url = new URL(req.url, `https://${req.headers.host || 'voyara.vercel.app'}`);
  const path = url.pathname.replace(/^\/api/, '') || '/';

  try {
    if (req.method === 'GET' && path === '/health') {
      sendJson(res, 200, { ok: true, service: 'voyara-api' });
      return;
    }

    if (req.method === 'GET' && path === '/destinations') {
      sendJson(res, 200, travelData);
      return;
    }

    if (req.method === 'GET' && path === '/packages') {
      const db = await readDb();
      sendJson(res, 200, [...packagesData, ...db.packages]);
      return;
    }

    if (req.method === 'POST' && path === '/packages') {
      const body = req.body || {};
      if (!body.title || !body.region || !body.destinations || !body.priceRaw) {
        sendJson(res, 400, { error: 'Package title, region, destinations, and price are required' });
        return;
      }

      const db = await readDb();
      const priceRaw = Number(body.priceRaw);
      const createdPackage = {
        id: `admin-${Date.now()}`,
        title: body.title,
        region: body.region,
        budget: body.budget || 'Middle Class',
        transport: body.transport || ['Flight', 'Hotel'],
        destinations: Array.isArray(body.destinations)
          ? body.destinations
          : String(body.destinations).split(',').map((item) => item.trim()).filter(Boolean),
        duration: body.duration || '4N / 5D',
        priceRaw,
        price: `Rs. ${priceRaw.toLocaleString('en-IN')}`,
        img: body.img || 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?q=80&w=600&auto=format&fit=crop',
        trending: Boolean(body.trending),
        features: body.features || ['Custom Package', 'Verified Stay', 'Flexible Booking'],
      };

      db.packages.unshift(createdPackage);
      await writeDb(db);
      sendJson(res, 201, createdPackage);
      return;
    }

    if (req.method === 'GET' && path === '/bookings') {
      const db = await readDb();
      sendJson(res, 200, db.bookings.sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt)));
      return;
    }

    if (req.method === 'GET' && path === '/admin/stats') {
      const db = await readDb();
      const revenue = db.bookings.reduce((sum, booking) => sum + Number(booking.amount || 0), 0);
      sendJson(res, 200, {
        bookings: db.bookings.length,
        customPackages: db.packages.length,
        revenue,
        destinations: new Set(db.bookings.map((booking) => booking.destination)).size,
      });
      return;
    }

    const ticketMatch = path.match(/^\/bookings\/([^/]+)\/ticket\.pdf$/);
    if (req.method === 'GET' && ticketMatch) {
      const db = await readDb();
      const booking = db.bookings.find((item) => item.id === ticketMatch[1]);
      if (!booking) {
        sendJson(res, 404, { error: 'Booking not found' });
        return;
      }

      const pdf = createTicketPdf(booking);
      res.setHeader('Content-Type', 'application/pdf');
      res.setHeader('Content-Disposition', `attachment; filename="${booking.id}-ticket.pdf"`);
      res.status(200).send(pdf);
      return;
    }

    if (req.method === 'POST' && path === '/ai/plan') {
      sendJson(res, 200, createAiPlan(req.body));
      return;
    }

    if (req.method === 'POST' && path === '/bookings') {
      const body = req.body || {};
      const validationError = validateBooking(body);
      if (validationError) {
        sendJson(res, 400, { error: validationError });
        return;
      }

      const db = await readDb();
      const booking = {
        id: `VYA-${Date.now().toString().slice(-6)}`,
        status: 'CONFIRMED',
        paymentStatus: 'PAID',
        createdAt: new Date().toISOString(),
        ...body,
      };

      db.bookings.unshift(booking);
      await writeDb(db);
      sendJson(res, 201, booking);
      return;
    }

    sendJson(res, 404, { error: 'Route not found' });
  } catch (error) {
    sendJson(res, 500, { error: error.message || 'Internal server error' });
  }
}
